"""
Advanced-mode SQL export: turns confirmed mappings (source table + source
field -> target table.field) into SELECT statements a technical data person
can run against the customer's live source database.

Scope, deliberately (see docs/PHASE_PLAN.md and chat record for why):
- No JOINs are ever generated. If a target table's mapped fields name more
  than one distinct source table, that's not an error — it just means that
  target table gets one SELECT statement per source table instead of one
  overall, each producing whichever subset of that table's columns came
  from that source table. The data person is responsible for merging those
  result sets themselves; this tool doesn't guess at how to join them.
- No automatic value-transformation logic (e.g. guessing that source "Y"/"N"
  means target 1/2) — this tool never fabricates rules about the customer's
  actual data. Required/decode constraints are surfaced as SQL comments for
  the data person to handle, not as generated CASE WHEN logic.
- Column aliases match the target field name exactly, so each result set can
  be dropped directly into that target table's staging data.
"""

from collections import defaultdict

DIALECTS = {
    "SQL Server": {"quote": lambda ident: f"[{ident}]"},
    "MySQL": {"quote": lambda ident: f"`{ident}`"},
    "PostgreSQL": {"quote": lambda ident: f'"{ident}"'},
    "Oracle": {"quote": lambda ident: f'"{ident}"'},
}

DEFAULT_DIALECT = "SQL Server"


def _quote_qualified(dialect, name):
    """'dbo.ClientExport' -> quote each dot-separated part separately,
    so a schema-qualified source table name doesn't get quoted as one
    (invalid) identifier."""
    quote = DIALECTS[dialect]["quote"]
    return ".".join(quote(part) for part in name.split(".") if part)


def _normalize_table_name(name):
    """Grouping key for "same table, different casing" (e.g. dbo.ClientExport
    vs dbo.clientexport). Only case differences are folded — anything else
    (extra whitespace already stripped by the caller, a different schema
    prefix, an actual typo) still counts as a different table."""
    return name.lower()


def _build_todo_header(check, skipped, dialect, target_label, source_system):
    """Assembles a SQL-comment preamble out of facts already computed
    elsewhere (schema_rules.check_batch, the skip list below) -- nothing
    here is inferred or fabricated, it's just organized so a data person
    who only has the downloaded .sql file still sees every open item
    without needing the web UI open next to it."""
    title = "ETL Starter Script"
    if source_system or target_label:
        title += " — " + " → ".join(p for p in (source_system, target_label) if p)
    lines = [
        "-- " + "=" * 70,
        f"-- {title} ({dialect})",
        "-- Generated by CW-ETL-FIELDMAP. This script only extracts and aliases",
        "-- columns -- it never guesses at value transformations. Resolve every",
        "-- TODO below before running this against a live system.",
        "-- " + "=" * 70,
    ]

    sections = []
    check = check or {}
    if check.get("requiredMissing"):
        sections.append((
            "Required target field(s) with no mapping yet",
            [f"{r['table']}.{r['field']}" for r in check["requiredMissing"]],
        ))
    if check.get("fkWarnings"):
        sections.append((
            "Missing dependent table(s)",
            [f"{w['table']}.{w['field']} references {w['dependsOn']}, which hasn't been mapped" for w in check["fkWarnings"]],
        ))
    if check.get("duplicates"):
        sections.append((
            "Target field(s) claimed by more than one source field",
            [f"{d['table']}.{d['field']} <- {', '.join(d['sourceFields'])}" for d in check["duplicates"]],
        ))
    if check.get("formatHints"):
        sections.append((
            "Possible value/format mismatches to double-check",
            [f"{h['sourceField']}: {h['hint']}" for h in check["formatHints"]],
        ))
    if skipped:
        sections.append((
            "Field(s) not included in the SELECT statements below",
            [f"{s['sourceField']} ({s['reason']})" for s in skipped],
        ))

    if not sections:
        lines.append("-- No outstanding TODOs from what this tool can check automatically.")
    else:
        for heading, items in sections:
            lines.append(f"-- TODO: {heading}:")
            for item in items:
                lines.append(f"--   - {item}")
    lines.append("-- " + "=" * 70)
    return "\n".join(lines)


def build_export(mappings, schema, dialect=DEFAULT_DIALECT, check=None, target_label=None, source_system=None):
    """
    mappings: list of {"sourceTable":str, "sourceField":str, "desc":str,
                        "table":str|None, "field":str|None, "flagged":bool}
    Only entries with a non-empty sourceTable AND a confirmed target
    table/field are usable; others are reported as skipped.

    check: optional schema_rules.check_batch(...) result for the same
    mappings/schema, folded into the returned "header" text as TODOs --
    this function never computes rule violations itself, just reports
    ones already found elsewhere so the downloaded script is self-contained.

    Returns {"statements": [{"targetTable", "sourceTable", "sql"}],
             "multiSourceTables": [{"targetTable", "sourceTables": [...]}],
             "skipped": [{"sourceField", "reason"}],
             "header": str}

    multiSourceTables is informational, not an error: it lists target
    tables whose data is split across more than one generated statement,
    so the UI can flag "you'll need to merge these yourself."
    """
    if dialect not in DIALECTS:
        dialect = DEFAULT_DIALECT

    by_table_field = {(f["table"], f["field"]): f for f in schema}

    usable = defaultdict(list)  # (target_table, normalized_source_table) -> [mapping,...]
    source_table_display = {}  # (target_table, normalized_source_table) -> first-seen casing
    skipped = []
    for m in mappings:
        if not (m.get("table") and m.get("field")):
            reason = "flagged for consultant review" if m.get("flagged") else "not mapped to a target field"
            skipped.append({"sourceField": m.get("sourceField", ""), "reason": reason})
            continue
        source_table = (m.get("sourceTable") or "").strip()
        if not source_table:
            skipped.append({"sourceField": m.get("sourceField", ""), "reason": "no source table specified"})
            continue
        key = (m["table"], _normalize_table_name(source_table))
        usable[key].append(m)
        source_table_display.setdefault(key, source_table)

    statements = []
    tables_by_target = defaultdict(set)
    for (target_table, norm_source), entries in usable.items():
        source_table = source_table_display[(target_table, norm_source)]
        tables_by_target[target_table].add(source_table)

        lines = [f"-- Target table: {target_table}  (source: {source_table})"]
        select_parts = []
        for e in entries:
            meta = by_table_field.get((target_table, e["field"]))
            if meta:
                notes = []
                if meta.get("required"):
                    notes.append("required")
                if meta.get("decode"):
                    notes.append(f"expects: {meta['decode']}")
                elif meta.get("type"):
                    notes.append(meta["type"])
                if notes:
                    lines.append(f"--   {target_table}.{e['field']}: {'; '.join(notes)} — verify source values match.")
            select_parts.append(
                f"    {_quote_qualified(dialect, e['sourceField'])} AS {DIALECTS[dialect]['quote'](e['field'])}"
            )

        lines.append("SELECT")
        lines.append(",\n".join(select_parts))
        lines.append(f"FROM {_quote_qualified(dialect, source_table)};")

        statements.append({"targetTable": target_table, "sourceTable": source_table, "sql": "\n".join(lines)})

    statements.sort(key=lambda s: (s["targetTable"], s["sourceTable"]))

    multi_source_tables = [
        {"targetTable": t, "sourceTables": sorted(sources)}
        for t, sources in tables_by_target.items()
        if len(sources) > 1
    ]
    multi_source_tables.sort(key=lambda m: m["targetTable"])

    header = _build_todo_header(check, skipped, dialect, target_label, source_system)

    return {"statements": statements, "multiSourceTables": multi_source_tables, "skipped": skipped, "header": header}
