"""
Advanced-mode SQL export: turns confirmed mappings (source table + source
field -> target table.field) into SELECT statements a technical data person
can run against the customer's live source database.

Scope, deliberately (see docs/PHASE_PLAN.md and chat record for why):
- No JOINs are ever generated. If a target table's mapped fields name more
  than one distinct source table, that's not an error — it just means that
  target table gets one SELECT statement per source table instead of one
  overall, each producing whichever subset of that table's columns came
  from that source table. The data person is responsible for merging those
  result sets themselves; this tool doesn't guess at how to join them.
- No value-transformation logic gets *guessed* (e.g. assuming source "Y"/"N"
  means target 1/2) — this tool never fabricates rules about the customer's
  actual data. The one narrow exception, transform_draft.py: when the
  customer's own typed description for a field and the target's own signed-
  off decode both parse into code=label pairs and every source label matches
  a target label exactly, that's not a guess — it's a mechanical join of two
  facts already on record for this migration, so a CASE WHEN gets drafted
  and clearly marked as a draft to verify. Anything short of that exact
  match (no description, an unparseable one, an unmatched label) stays a
  plain column alias plus a comment, same as always. Required/decode
  constraints in general are still just surfaced as SQL comments.
- format_rules.py bakes a second, narrower kind of rule straight into the
  column expression, with no draft/review step: SSN dashing, phone/fax
  cleanup, zip default+truncation, and name truncation/null-fallback. These
  are safe to apply outright (not just draft) because they're sourced from
  CaseWorthy's own production migration scripts (reference/MASTER_*.sql),
  not inferred from this customer's data -- and for that same reason they're
  CaseWorthy-only, never applied when exporting for another target database.
- Column aliases match the target field name exactly, so each result set can
  be dropped directly into that target table's staging data.
"""

from collections import defaultdict

import format_rules
import transform_draft

DIALECTS = {
    "SQL Server": {"quote": lambda ident: f"[{ident}]"},
    "MySQL": {"quote": lambda ident: f"`{ident}`"},
    "PostgreSQL": {"quote": lambda ident: f'"{ident}"'},
    "Oracle": {"quote": lambda ident: f'"{ident}"'},
}

DEFAULT_DIALECT = "SQL Server"


def _quote_qualified(dialect, name):
    """'dbo.ClientExport' -> quote each dot-separated part separately,
    so a schema-qualified source table name doesn't get quoted as one
    (invalid) identifier."""
    quote = DIALECTS[dialect]["quote"]
    return ".".join(quote(part) for part in name.split(".") if part)


def _normalize_table_name(name):
    """Grouping key for "same table, different casing" (e.g. dbo.ClientExport
    vs dbo.clientexport). Only case differences are folded — anything else
    (extra whitespace already stripped by the caller, a different schema
    prefix, an actual typo) still counts as a different table."""
    return name.lower()


def _build_todo_header(
    check, skipped, dialect, target_label, source_system, drafted, draft_failures, draft_suggestions,
    formats_applied,
):
    """Assembles a SQL-comment preamble out of facts already computed
    elsewhere (schema_rules.check_batch, the skip list below) -- nothing
    here is inferred or fabricated, it's just organized so a data person
    who only has the downloaded .sql file still sees every open item
    without needing the web UI open next to it."""
    title = "ETL Starter Script"
    if source_system or target_label:
        title += " — " + " → ".join(p for p in (source_system, target_label) if p)
    lines = [
        "-- " + "=" * 70,
        f"-- {title} ({dialect})",
        "-- Generated by CW-ETL-FIELDMAP. This script only extracts and aliases",
        "-- columns -- it never guesses at value transformations. Resolve every",
        "-- TODO below before running this against a live system.",
        "-- " + "=" * 70,
    ]

    sections = []
    check = check or {}
    if check.get("requiredMissing"):
        sections.append((
            "Required target field(s) with no mapping yet",
            [f"{r['table']}.{r['field']}" for r in check["requiredMissing"]],
        ))
    if check.get("fkWarnings"):
        sections.append((
            "Missing dependent table(s)",
            [f"{w['table']}.{w['field']} references {w['dependsOn']}, which hasn't been mapped" for w in check["fkWarnings"]],
        ))
    if check.get("duplicates"):
        sections.append((
            "Target field(s) claimed by more than one source field",
            [f"{d['table']}.{d['field']} <- {', '.join(d['sourceFields'])}" for d in check["duplicates"]],
        ))
    if check.get("formatHints"):
        sections.append((
            "Possible value/format mismatches to double-check",
            [f"{h['sourceField']}: {h['hint']}" for h in check["formatHints"]],
        ))
    if formats_applied:
        sections.append(("Formatting rule(s) baked into the SELECT columns below", formats_applied))
    if drafted:
        sections.append(("Value mapping(s) drafted below — review before running", drafted))
    if draft_failures:
        sections.append(("Decode mapping(s) that could not be auto-drafted", draft_failures))
    if draft_suggestions:
        sections.append(("Possible source-value pattern(s) from past confirmed mappings", draft_suggestions))
    if skipped:
        sections.append((
            "Field(s) not included in the SELECT statements below",
            [f"{s['sourceField']} ({s['reason']})" for s in skipped],
        ))

    if not sections:
        lines.append("-- No outstanding TODOs from what this tool can check automatically.")
    else:
        for heading, items in sections:
            lines.append(f"-- TODO: {heading}:")
            for item in items:
                lines.append(f"--   - {item}")
    lines.append("-- " + "=" * 70)
    return "\n".join(lines)


def build_export(
    mappings, schema, dialect=DEFAULT_DIALECT, check=None, target_label=None, source_system=None,
    decode_patterns=None, target_database=None,
):
    """
    mappings: list of {"sourceTable":str, "sourceField":str, "desc":str,
                        "table":str|None, "field":str|None, "flagged":bool}
    Only entries with a non-empty sourceTable AND a confirmed target
    table/field are usable; others are reported as skipped.

    check: optional schema_rules.check_batch(...) result for the same
    mappings/schema, folded into the returned "header" text as TODOs --
    this function never computes rule violations itself, just reports
    ones already found elsewhere so the downloaded script is self-contained.

    decode_patterns: optional {(target_table, target_field): [{"desc","count"}]}
    of past confirmed mappings' descriptions for fields being exported here --
    see transform_draft.py. Only ever used as a fallback when a mapping's own
    `desc` doesn't itself produce a usable value-transform draft.

    target_database: the schema_rules.TARGET_DATABASES key (e.g. "CaseWorthy"),
    not target_label's display name -- gates format_rules.py, whose baked
    formatting rules are sourced only from CaseWorthy's own migration scripts
    and must never be applied when exporting for another target database.

    Returns {"statements": [{"targetTable", "sourceTable", "sql"}],
             "multiSourceTables": [{"targetTable", "sourceTables": [...]}],
             "skipped": [{"sourceField", "reason"}],
             "header": str}

    multiSourceTables is informational, not an error: it lists target
    tables whose data is split across more than one generated statement,
    so the UI can flag "you'll need to merge these yourself."
    """
    if dialect not in DIALECTS:
        dialect = DEFAULT_DIALECT

    by_table_field = {(f["table"], f["field"]): f for f in schema}

    # Exact-case field name per (table, lowercased field name) -- lets the
    # companion-field synthesis below look up "does Client have a
    # SSNDataQuality column" without caring how the customer capitalized SSN.
    fields_by_table_lower = defaultdict(dict)
    for f in schema:
        fields_by_table_lower[f["table"]][f["field"].lower()] = f["field"]

    bake_formats = target_database == "CaseWorthy"

    usable = defaultdict(list)  # (target_table, normalized_source_table) -> [mapping,...]
    source_table_display = {}  # (target_table, normalized_source_table) -> first-seen casing
    skipped = []
    for m in mappings:
        if not (m.get("table") and m.get("field")):
            reason = "flagged for consultant review" if m.get("flagged") else "not mapped to a target field"
            skipped.append({"sourceField": m.get("sourceField", ""), "reason": reason})
            continue
        source_table = (m.get("sourceTable") or "").strip()
        if not source_table:
            skipped.append({"sourceField": m.get("sourceField", ""), "reason": "no source table specified"})
            continue
        key = (m["table"], _normalize_table_name(source_table))
        usable[key].append(m)
        source_table_display.setdefault(key, source_table)

    decode_patterns = decode_patterns or {}
    drafted, draft_failures, draft_suggestions, formats_applied = [], [], [], []

    statements = []
    tables_by_target = defaultdict(set)
    for (target_table, norm_source), entries in usable.items():
        source_table = source_table_display[(target_table, norm_source)]
        tables_by_target[target_table].add(source_table)

        lines = [f"-- Target table: {target_table}  (source: {source_table})"]
        select_parts = []
        mapped_fields_lower = {}  # field.lower() -> quoted source, for companion synthesis below
        for e in entries:
            meta = by_table_field.get((target_table, e["field"]))
            quoted_source = _quote_qualified(dialect, e["sourceField"])
            quoted_target = DIALECTS[dialect]["quote"](e["field"])
            column_expr = quoted_source
            mapped_fields_lower[e["field"].lower()] = quoted_source
            if meta:
                target_field_label = f"{target_table}.{e['field']}"
                notes = []
                if meta.get("required"):
                    notes.append("required")
                if meta.get("decode"):
                    notes.append(f"expects: {meta['decode']}")
                elif meta.get("type"):
                    notes.append(meta["type"])
                if notes:
                    lines.append(f"--   {target_field_label}: {'; '.join(notes)} — verify source values match.")

                draft = transform_draft.draft_or_explain(
                    dialect, quoted_source, target_field_label, meta, e.get("desc", ""),
                    decode_patterns.get((target_table, e["field"]), []),
                )
                if draft["kind"] == "drafted":
                    column_expr = draft["sql"]
                    lines.append(f"--   {target_field_label}: value mapping drafted below — review before running.")
                    drafted.append(f"via {e['sourceField']}: {draft['note']}")
                elif draft["kind"] == "failed":
                    draft_failures.append(f"via {e['sourceField']}: {draft['note']}")
                elif draft["kind"] == "suggested":
                    draft_suggestions.append(f"via {e['sourceField']}: {draft['note']}")
                elif bake_formats:
                    fmt = format_rules.column_rule(quoted_source, meta)
                    if fmt:
                        column_expr = fmt["sql"]
                        lines.append(f"--   {target_field_label}: formatting rule baked in — {fmt['note']}")
                        formats_applied.append(f"{target_field_label} (via {e['sourceField']}): {fmt['note']}")
            select_parts.append(f"    {column_expr} AS {quoted_target}")

        if bake_formats:
            for anchor_lower, quoted_anchor in list(mapped_fields_lower.items()):
                companion_lower = format_rules.companion_field_lower(anchor_lower)
                if not companion_lower or companion_lower in mapped_fields_lower:
                    continue
                companion_field = fields_by_table_lower.get(target_table, {}).get(companion_lower)
                if not companion_field:
                    continue
                fmt = format_rules.companion_rule(anchor_lower, quoted_anchor)
                if not fmt:
                    continue
                target_field_label = f"{target_table}.{companion_field}"
                quoted_target = DIALECTS[dialect]["quote"](companion_field)
                select_parts.append(f"    {fmt['sql']} AS {quoted_target}")
                lines.append(f"--   {target_field_label}: derived from the same source value as its anchor field — {fmt['note']}")
                formats_applied.append(f"{target_field_label} (derived, no source field of its own): {fmt['note']}")

        lines.append("SELECT")
        lines.append(",\n".join(select_parts))
        lines.append(f"FROM {_quote_qualified(dialect, source_table)};")

        statements.append({"targetTable": target_table, "sourceTable": source_table, "sql": "\n".join(lines)})

    statements.sort(key=lambda s: (s["targetTable"], s["sourceTable"]))

    multi_source_tables = [
        {"targetTable": t, "sourceTables": sorted(sources)}
        for t, sources in tables_by_target.items()
        if len(sources) > 1
    ]
    multi_source_tables.sort(key=lambda m: m["targetTable"])

    header = _build_todo_header(
        check, skipped, dialect, target_label, source_system, drafted, draft_failures, draft_suggestions,
        formats_applied,
    )

    return {"statements": statements, "multiSourceTables": multi_source_tables, "skipped": skipped, "header": header}
