USE Replace_ME_ETL
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MASTERREFERRAL' AND COLUMN_NAME = 'LegacyID')
BEGIN
	ALTER TABLE dbo.MASTERREFERRAL ADD LegacyID VARCHAR(20) NULL;
END
GO

---11999 of 11999
INSERT INTO MASTERREFERRAL (CREATEDDATE, PREFERREDSTARTDATE, CREATEDBY, ENROLLMENTID
, CASENOTEID, MASTERREFERRALTYPE, RESTRICTION, OWNEDBYORGID
, MASTERREFERRALBATCHID, REFERREDENTITYID, ACCOUNTID, LegacyID)
SELECT
M.CREATEDDATE
, M.PREFERREDSTARTDATE
, U.EntityiD AS CREATEDBY
, E.ENROLLMENTID
, C.CASENOTEID
, M.MASTERREFERRALTYPE
, M.RESTRICTION
, M.OWNEDBYORGID
, M.MASTERREFERRALBATCHID
, Cl.EntityID AS REFERREDENTITYID
, M.ACCOUNTID
, M.MASTERREFERRALID AS LegacyID
FROM Replace_ME_Staging.dbo.XMASTERREFERRAL M
LEFT JOIN Enrollment E on E.LegacyID = M.EnrollmentID
LEFT JOIN CaseNotes C on C.LegacyID = M.CasenoteID
LEFT JOIN Users U on U.LegacyID = M.CreatedBy
LEFT JOIN Client Cl on Cl.LegacyID = M.REFERREDENTITYID
LEFT JOIN MASTERREFERRAL M2 on M2.LegacyID = M.MASTERREFERRALID
WHERE M2.MasterReferralID IS NULL
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PROGRAMREFERRAL' AND COLUMN_NAME = 'LegacyID')
BEGIN
	ALTER TABLE dbo.PROGRAMREFERRAL ADD LegacyID VARCHAR(20) NULL;
END
GO

--11999 of 11999
INSERT INTO PROGRAMREFERRAL (CREATEDDATE, CREATEDBY, ENTITYID
, PROGRAMREFERRALTYPEID, CASENOTEID, REFERREDTOUSERID
, MATCHRANK, RESTRICTION, OWNEDBYORGID, MASTERREFERRALID
, STATUS, PROGRAMID, REFERREDDATE, LegacyID)
SELECT
 PR.CREATEDDATE
, PR.CREATEDBY
, Cl.ENTITYID AS ENTITYID
, PR.PROGRAMREFERRALTYPEID
, C.CASENOTEID
, PR.REFERREDTOUSERID
, PR.MATCHRANK
, PR.RESTRICTION
, PR.OWNEDBYORGID
, MR.MasterReferralID AS MASTERREFERRALID
, PR.[STATUS]
, P.PROGRAMID
, PR.REFERREDDATE
, PR.PROGRAMREFERRALID AS LegactID
FROM Replace_ME_Staging.dbo.XPROGRAMREFERRAL PR
LEFT JOIN CaseNotes C on C.LegacyID = PR.CasenoteID
LEFT JOIN Users U on U.LegacyID = PR.CreatedBy
LEFT JOIN Client Cl on Cl.LegacyID = PR.EntityID
LEFT JOIN Program P ON P.LegacyID = PR.PROGRAMID
LEFT JOIN MASTERREFERRAL MR ON MR.LegacyID = PR.MasterReferralID
LEFT JOIN PROGRAMREFERRAL PR2 on PR2.LegacyID = PR.PROGRAMREFERRALID
WHERE PR2.ProgramReferralID IS NULL --prevent dupes
